### ISSUE TITLE
"Hello world" example from Wikipedia does not work correctly

### ISSUE THREAD

**Issue by crumblingstatue** [smoqadam/rust-brainfuck#3]
From https://en.wikipedia.org/wiki/Brainfuck

`++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.+++.------.--------.>>+.>++.`

In debug mode, it panics with `thread 'main' panicked at 'attempt to subtract with overflow', src/main.rs:42`.
In release mode, it's stuck in an infinite loop.

I won't spoil the fun of fixing this bug, but we can discuss the problem in this thread if you'd like.

**Comment by smoqadam** [comment]
Thanks. 
please test it again. I made some change. I think it works now

**Comment by crumblingstatue** [comment]
It indeed does work now.
